[build]
builder = "dockerfile"
dockerfilePath = "MercadoPagoAPI/Dockerfile"

[deploy]
startCommand = "dotnet MercadoPagoAPI.dll"
restartPolicyType = "always"
healthcheckPath = "/test/health"
sleep = false