[build]
builder = "dockerfile"
dockerfilePath = "MercadoPagoAPI/Dockerfile"

[deploy]
startCommand = "dotnet MercadoPagoAPI.dll"
restartPolicyType = "always"
healthcheckPath = "/api/test/health"
sleep = false